controller_manager_ns: controller_manager
controller_list:
  - name: mra7a/arm_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
      - Joint7

  - name: mra7a/gripper_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - left_gripper_Joint
      - right_gripper_Joint
