controller_list:
  - name: fake_arm_controller
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
      - Joint7
  - name: fake_gripper_controller
    joints:
      - left_gripper_Joint
      - right_gripper_Joint